### ISSUE TITLE
document validation 

### ISSUE THREAD

**Issue by elycheikhsmail** [oslabs-beta/dangoDB#46]
How to validate object using dangoDB ?

**Comment by wgreco13** [comment]
Hi, elycheikhsmail. Could you please further describe your question so that I can properly address it?

**Comment by elycheikhsmail** [comment]
I not yet try dango but in the readme I see schama describing object, I think we can make : 
```
const result = mymodel.validation(someobject)
```
and result give missing key in given object and all errors

**Comment by wgreco13** [comment]
The `validator` option is a property that can be defined in the Schema Options object, it is not a method that can be called on the model. It is defined as either null by default or by user input. It must be a function that returns a boolean when the value of a given insertion/update query is passed into it. It is essentially a user-defined way of ensuring that a given value satisfies some criteria. For example, if the schema requires a number, the validator function could return true if the number is > 5. On any insertion/update queries thereafter the validator function would only 'pass' if the new entry had a value > 5. I hope this answers your question!
