### ISSUE TITLE
Auth mechanism not work with Mongo Altas

### ISSUE THREAD

**Issue by Jess182** [oslabs-beta/dangoDB#56]
### Environment
- deno 1.24.3 (release, x86_64-apple-darwin)
- v8 10.4.132.20
- typescript 4.7.4
- dango: v1.0.3

When i try to connect to Mongo Atlas, I get follow error:
```
error: Uncaught (in promise) Error: Could not connect to database. Error: MongoError: "Connection failed: MongoError: {\"ok\":0,\"errmsg\":\"auth mechanism SCRAM-SHA-256 is not supported\",\"code\":8000,\"codeName\":\"AtlasError\"}"
      throw new Error(`Could not connect to database. ${error}`);
```

**Comment by germancgn** [comment]
Deno's Mongo driver does not support the `SCRAM-SHA-256` authentication mechanism. You have to use `SCRAM-SHA-1` instead by setting the `authMechanism` parameter in the connection string like this:

```typescript
await dango.connect(`mongodb+srv://${username}:${password}@${cluster}.mongodb.net/test?authMechanism=SCRAM-SHA-1`);
```

**Comment by Jess182** [comment]
Thanks @unpin !
